spring.application.name=flash-ticket-backend

# Server Port
server.port=8000

# Database PostgreSQL Connection (Docker container ticket_postgres)
spring.datasource.url=jdbc:postgresql://localhost:5433/ticket_db
spring.datasource.username=postgres
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# REDIS CONFIGURATIONS
spring.data.redis.host=localhost
spring.data.redis.port=6380
spring.cache.redis.cache-null-values=false

# Debug Logging untuk Spring Cache dan Redis
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis=TRACE